[package]
name = "ace"
version = "0.1.0"
edition = "2021"

[lib]
name = "ace"
crate-type = ["cdylib"]

[dependencies]
arma-rs = { version = "1.8.0", features = ["uuid"] }
uuid = { version = "1.1.2", features = ["v4"] }
rand = "0.8.5"
rand_chacha = "0.3.1"

# Artillery
rayon = "1.5.3"

# Clipboard
clipboard = { version = "0.5", optional = true }

[features]
default = ["clipboard"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
