branches:
  only:
    - master
language: python
python:
  - "3.4"
before_script:
  - pip install pygithub
  - pip install pygithub3
script:
  - python3 tools/deploy.py
  - python3 tools/sqf_validator.py
env:
  global:
    - secure: "KcJQbknBOdC5lA4nFGKPXVRVIGLDXDRzC8XkHuXJCE9pIR/wbxbkvx8fHKcC6SC9eHgzneC3+o4m4+CjIbVvIwDgslRbJ8Y59i90ncONmdoRx1HUYHwuYWVZm9HJFjCsIbrEqhSyyKS+PB3WZVOLbErtNHsgS8f43PTh5Ujg7Vg="
