name = "ACE3"
prefix = "ace"
author = "ACE-Team"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_DE.md",
    "docs/README_PL.md",
    "README.zh-TW.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ace3_ca.paa",
    "meta.cpp"
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip ace3_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
