[default]
workshop = [
    "450814997", # CBA_A3
]

[spe]
extends = "default"
dlc = [
    "Spearhead 1944"
]

[vn]
extends = "default"
dlc = [
    "S.O.G. Prairie Fire",
]

[ws]
extends = "default"
dlc = [
    "Western Sahara",
]

[rf]
extends = "default"
dlc = [
    "Reaction Forces"
]

[gm]
extends = "default"
dlc = [
    "Global Mobilization - Cold War Germany"
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "541888371", # CUP Vehicles
    "497661914", # CUP Units
]

[cfp]
extends = "cup"
workshop = [
    "1369691841", # Community Factions Project
]

[wardrobe]
extends = "default"
mission = "Wardrobe.VR"
workshop = [
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
#    "623475643",  # eden enhanced
]
