[default]
workshop = [
    "450814997", # CBA_A3
    "2369477168", # Advanced Developer Tools's Workshop ID
    "1779063631", # ZEN
]

[spe]
extends = "default"
dlc = [
    "Spearhead 1944"
]

[vn]
extends = "default"
dlc = [
    "S.O.G. Prairie Fire",
]

[ws]
extends = "default"
dlc = [
    "Western Sahara",
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]
