[default]
workshop = [
    "450814997", # CBA_A3
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "541888371", # CUP Vehicles
    "497661914", # CUP Units
]

[cfp]
extends = "cup"
workshop = [
    "1369691841", # Community Factions Project
]

[wardrobe]
extends = "default"
mission = "Wardrobe.VR"
workshop = [
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
#   "751965892",  # ACRE
#   "623475643",  # eden enhanced
]

[sogns]
extends = "default"
dlc = ["vn"]
workshop = [
    "623475643",  # 3den Enhanced
    "3499977893", # Advanced Developer Tools
    "3083451905", # S.O.G. Nickel Steel
    "1779063631", # Zeus Enhanced
]
