name = "ACE3"
prefix = "ace"
author = "ACE-Team"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README*.md",  # Translated READMEs get moved to root in a hook (virtual file system)
    "AUTHORS.txt",
    "LICENSE",
    "logo_ace3_ca.paa",
    "meta.cpp",
]

[version]
git_hash = 0

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
    "/dev/",
    "medical_ai/statemachine.sqf",
    "common/functions/fnc_dummy.sqf",
    "zeus/functions/fnc_zeusAttributes.sqf",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3
]

[hemtt.launch.spe]
workshop = [
    "450814997", # CBA_A3
]
dlc = [
    "spe"
]

[hemtt.launch.vn]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "S.O.G. Prairie Fire",
]

[hemtt.launch.ws]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "Western Sahara",
]
