title: ACE3
description: ACE3 is a joint effort by the teams behind ACE 2, AGM and CSE to improve the realism and authenticity of Arma 3.
keywords: Advanced Combat Enhancement 3, ACE, ACE3, Arma, Arma 3, Mod, Modification, Realism, AGM, CSE, Bohemia, Interactive

productionUrl: http://localhost:4000

ace:
  githubUrl: https://github.com/acemod/ACE3
  version:
    major: 3
    minor: 20
    patch: 2
    build: 108


markdown: kramdown
kramdown:
  input: GFM

timezone: UTC

excerpt_separator: <!--more-->

highlighter: rouge

safe: true
lsi: false

exclude: [src, .editorconfig, .gitignore, CNAME, Gemfile, Gemfile.lock, README*.md, Dockerfile, docker-compose.yml, entrypoint.sh, package-lock.json, acebot.json]

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
