name: ACE3
description: ACE3 is a joint effort by the teams behind ACE 2, AGM and CSE to improve the realism and authenticity of Arma 3.
keywords: Advanced Combat Enhancement 3, ACE, ACE3, Arma, Arma 3, Mod, Modification, Realism, AGM, CSE, Bohemia, Interactive

productionUrl: https://ace3mod.com

ace:
  githubUrl: https://github.com/acemod/ACE3
  version:
    major: 3
    minor: 14
    patch: 3
    build: 55

acex:
  githubUrl: https://github.com/acemod/ACEX
  version:
    major: 3
    minor: 5
    patch: 4
    build: 23


markdown: kramdown
kramdown:
  input: GFM

timezone: UTC

excerpt_separator: <!--more-->

highlighter: rouge

safe: true
lsi: false

exclude: [src, .editorconfig, .gitignore, CNAME, Gemfile, Gemfile.lock, README.md]

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
