version: "3.2"

services:
  docs:
    container_name: ace3mod_jekyll
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JEKYLLARGS=--incremental
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
